//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GanBao.Module.BusinessObjects.ganbaodb
{

    public partial class Dictionary : XPObject
    {
        string fCode;
        [Size(20)]
        [DevExpress.Xpo.DisplayName(@"编码")]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        [Size(80)]
        [DevExpress.Xpo.DisplayName(@"名称")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fOrderId;
        [DevExpress.Xpo.DisplayName(@"顺序")]
        public int OrderId
        {
            get { return fOrderId; }
            set { SetPropertyValue<int>(nameof(OrderId), ref fOrderId, value); }
        }
        string fPinYin;
        [Size(80)]
        [DevExpress.Xpo.DisplayName(@"拼音首字母")]
        public string PinYin
        {
            get { return fPinYin; }
            set { SetPropertyValue<string>(nameof(PinYin), ref fPinYin, value); }
        }
    }

}
