//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GanBao.Module.BusinessObjects.ganbaodb
{

    [BosCap("任务")]
    public partial class EventBase : XPObject
    {
        DateTime fBeginTime;
        [DevExpress.Xpo.DisplayName(@"开始时间")]
        public DateTime BeginTime
        {
            get { return fBeginTime; }
            set { SetPropertyValue<DateTime>(nameof(BeginTime), ref fBeginTime, value); }
        }
        DateTime fEndTime;
        [DevExpress.Xpo.DisplayName(@"结束时间")]
        public DateTime EndTime
        {
            get { return fEndTime; }
            set { SetPropertyValue<DateTime>(nameof(EndTime), ref fEndTime, value); }
        }
        string fAddress;
        [Size(80)]
        [DevExpress.Xpo.DisplayName(@"地址")]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fName;
        [Size(80)]
        [DevExpress.Xpo.DisplayName(@"保健对象卡号/姓名")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        WorkType fWorkType;
        public WorkType WorkType
        {
            get { return fWorkType; }
            set { SetPropertyValue<WorkType>(nameof(WorkType), ref fWorkType, value); }
        }
        Department fDepartment;
        public Department Department
        {
            get { return fDepartment; }
            set { SetPropertyValue<Department>(nameof(Department), ref fDepartment, value); }
        }
        OperatorType fOperatorType;
        [DevExpress.Xpo.DisplayName(@"人员类别")]
        public OperatorType OperatorType
        {
            get { return fOperatorType; }
            set { SetPropertyValue<OperatorType>(nameof(OperatorType), ref fOperatorType, value); }
        }
        string fRemark;
        [Size(200)]
        [DevExpress.Xpo.DisplayName(@"备注")]
        public string Remark
        {
            get { return fRemark; }
            set { SetPropertyValue<string>(nameof(Remark), ref fRemark, value); }
        }
    }

}
