//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GanBao.Module.BusinessObjects.ganbaodb
{

    [MapInheritance(MapInheritanceType.ParentTable)]
    [BosCap("干保任务")]
    public partial class GanBaoEvent : EventBase
    {
    }

}
