//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 公司 : XPObject
    {
        string f简称;
        [Size(20)]
        public string 简称
        {
            get { return f简称; }
            set { SetPropertyValue<string>(nameof(简称), ref f简称, value); }
        }
        string f全称;
        [Size(200)]
        public string 全称
        {
            get { return f全称; }
            set { SetPropertyValue<string>(nameof(全称), ref f全称, value); }
        }
        string f总部所在城市;
        [Size(80)]
        public string 总部所在城市
        {
            get { return f总部所在城市; }
            set { SetPropertyValue<string>(nameof(总部所在城市), ref f总部所在城市, value); }
        }
        string f登陆名称;
        [Size(40)]
        public string 登陆名称
        {
            get { return f登陆名称; }
            set { SetPropertyValue<string>(nameof(登陆名称), ref f登陆名称, value); }
        }
        职工 f核验人;
        public 职工 核验人
        {
            get { return f核验人; }
            set { SetPropertyValue<职工>(nameof(核验人), ref f核验人, value); }
        }
        bool f已核验;
        public bool 已核验
        {
            get { return f已核验; }
            set { SetPropertyValue<bool>(nameof(已核验), ref f已核验, value); }
        }
        decimal f注册资本;
        public decimal 注册资本
        {
            get { return f注册资本; }
            set { SetPropertyValue<decimal>(nameof(注册资本), ref f注册资本, value); }
        }
        string f数据治理大会2023问题;
        [Size(SizeAttribute.Unlimited)]
        public string 数据治理大会2023问题
        {
            get { return f数据治理大会2023问题; }
            set { SetPropertyValue<string>(nameof(数据治理大会2023问题), ref f数据治理大会2023问题, value); }
        }
        string f数据治理大会2023案例;
        [Size(SizeAttribute.Unlimited)]
        public string 数据治理大会2023案例
        {
            get { return f数据治理大会2023案例; }
            set { SetPropertyValue<string>(nameof(数据治理大会2023案例), ref f数据治理大会2023案例, value); }
        }
        [Association(@"厂商员工References公司"), Aggregated]
        public XPCollection<厂商员工> 厂商员工s { get { return GetCollection<厂商员工>(nameof(厂商员工s)); } }
    }

}
