//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 厂商员工 : XPObject
    {
        string f姓名;
        [Size(80)]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>(nameof(姓名), ref f姓名, value); }
        }
        公司 f公司;
        [Association(@"厂商员工References公司")]
        public 公司 公司
        {
            get { return f公司; }
            set { SetPropertyValue<公司>(nameof(公司), ref f公司, value); }
        }
        string f职位;
        [Size(20)]
        public string 职位
        {
            get { return f职位; }
            set { SetPropertyValue<string>(nameof(职位), ref f职位, value); }
        }
        string f所在城市;
        [Size(80)]
        public string 所在城市
        {
            get { return f所在城市; }
            set { SetPropertyValue<string>(nameof(所在城市), ref f所在城市, value); }
        }
        string f电话;
        [Size(20)]
        public string 电话
        {
            get { return f电话; }
            set { SetPropertyValue<string>(nameof(电话), ref f电话, value); }
        }
        bool f是否在省医院驻场;
        public bool 是否在省医院驻场
        {
            get { return f是否在省医院驻场; }
            set { SetPropertyValue<bool>(nameof(是否在省医院驻场), ref f是否在省医院驻场, value); }
        }
    }

}
