//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 字典 : XPObject
    {
        string f名称;
        [Size(80)]
        public string 名称
        {
            get { return f名称; }
            set { SetPropertyValue<string>(nameof(名称), ref f名称, value); }
        }
        int f顺序;
        public int 顺序
        {
            get { return f顺序; }
            set { SetPropertyValue<int>(nameof(顺序), ref f顺序, value); }
        }
        string f编码;
        [Size(80)]
        public string 编码
        {
            get { return f编码; }
            set { SetPropertyValue<string>(nameof(编码), ref f编码, value); }
        }
    }

}
