//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 巡检凭证 : XPObject
    {
        巡检 f巡检;
        [Association(@"巡检凭证References巡检")]
        public 巡检 巡检
        {
            get { return f巡检; }
            set { SetPropertyValue<巡检>(nameof(巡检), ref f巡检, value); }
        }
        DevExpress.Persistent.BaseImpl.FileData f图片;
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Persistent.Base.ExpandObjectMembers(DevExpress.Persistent.Base.ExpandObjectMembers.Never)]
        public DevExpress.Persistent.BaseImpl.FileData 图片
        {
            get { return f图片; }
            set { SetPropertyValue<DevExpress.Persistent.BaseImpl.FileData>(nameof(图片), ref f图片, value); }
        }
    }

}
