//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 巡检 : XPObject
    {
        系统 f系统;
        [Association(@"巡检References系统")]
        public 系统 系统
        {
            get { return f系统; }
            set { SetPropertyValue<系统>(nameof(系统), ref f系统, value); }
        }
        DateTime f巡检时间;
        public DateTime 巡检时间
        {
            get { return f巡检时间; }
            set { SetPropertyValue<DateTime>(nameof(巡检时间), ref f巡检时间, value); }
        }
        厂商员工 f巡检人;
        public 厂商员工 巡检人
        {
            get { return f巡检人; }
            set { SetPropertyValue<厂商员工>(nameof(巡检人), ref f巡检人, value); }
        }
        bool f信息中心已核验;
        public bool 信息中心已核验
        {
            get { return f信息中心已核验; }
            set { SetPropertyValue<bool>(nameof(信息中心已核验), ref f信息中心已核验, value); }
        }
        [Association(@"巡检凭证References巡检"), Aggregated]
        public XPCollection<巡检凭证> 巡检凭证s { get { return GetCollection<巡检凭证>(nameof(巡检凭证s)); } }
    }

}
