//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 服务器 : XPObject
    {
        string fIP地址;
        [Size(15)]
        public string IP地址
        {
            get { return fIP地址; }
            set { SetPropertyValue<string>(nameof(IP地址), ref fIP地址, value); }
        }
        string f服务器名;
        [Size(80)]
        public string 服务器名
        {
            get { return f服务器名; }
            set { SetPropertyValue<string>(nameof(服务器名), ref f服务器名, value); }
        }
        string f服务器用户名;
        [Size(20)]
        public string 服务器用户名
        {
            get { return f服务器用户名; }
            set { SetPropertyValue<string>(nameof(服务器用户名), ref f服务器用户名, value); }
        }
        string f服务器密码;
        [Size(20)]
        public string 服务器密码
        {
            get { return f服务器密码; }
            set { SetPropertyValue<string>(nameof(服务器密码), ref f服务器密码, value); }
        }
        string f服务器进程名;
        [Size(80)]
        public string 服务器进程名
        {
            get { return f服务器进程名; }
            set { SetPropertyValue<string>(nameof(服务器进程名), ref f服务器进程名, value); }
        }
        string f服务器进程端口;
        [Size(5)]
        public string 服务器进程端口
        {
            get { return f服务器进程端口; }
            set { SetPropertyValue<string>(nameof(服务器进程端口), ref f服务器进程端口, value); }
        }
        string f操作系统;
        [Size(80)]
        public string 操作系统
        {
            get { return f操作系统; }
            set { SetPropertyValue<string>(nameof(操作系统), ref f操作系统, value); }
        }
        string f数据库名;
        [Size(80)]
        public string 数据库名
        {
            get { return f数据库名; }
            set { SetPropertyValue<string>(nameof(数据库名), ref f数据库名, value); }
        }
        string f数据库用户名;
        [Size(80)]
        public string 数据库用户名
        {
            get { return f数据库用户名; }
            set { SetPropertyValue<string>(nameof(数据库用户名), ref f数据库用户名, value); }
        }
        string f数据库密码;
        [Size(80)]
        public string 数据库密码
        {
            get { return f数据库密码; }
            set { SetPropertyValue<string>(nameof(数据库密码), ref f数据库密码, value); }
        }
        服务器 f上级服务器;
        public 服务器 上级服务器
        {
            get { return f上级服务器; }
            set { SetPropertyValue<服务器>(nameof(上级服务器), ref f上级服务器, value); }
        }
        string f说明;
        [Size(200)]
        public string 说明
        {
            get { return f说明; }
            set { SetPropertyValue<string>(nameof(说明), ref f说明, value); }
        }
        string f资源增量2024;
        [Size(200)]
        public string 资源增量2024
        {
            get { return f资源增量2024; }
            set { SetPropertyValue<string>(nameof(资源增量2024), ref f资源增量2024, value); }
        }
        [Association(@"服务器References系统")]
        public XPCollection<系统> 系统s { get { return GetCollection<系统>(nameof(系统s)); } }
    }

}
