//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 系统付费 : XPObject
    {
        系统 f系统;
        [Association(@"系统付费References系统")]
        public 系统 系统
        {
            get { return f系统; }
            set { SetPropertyValue<系统>(nameof(系统), ref f系统, value); }
        }
        decimal f费用;
        public decimal 费用
        {
            get { return f费用; }
            set { SetPropertyValue<decimal>(nameof(费用), ref f费用, value); }
        }
        系统付费类型 f类型;
        public 系统付费类型 类型
        {
            get { return f类型; }
            set { SetPropertyValue<系统付费类型>(nameof(类型), ref f类型, value); }
        }
        DateTime f付费时间;
        public DateTime 付费时间
        {
            get { return f付费时间; }
            set { SetPropertyValue<DateTime>(nameof(付费时间), ref f付费时间, value); }
        }
        string f合同编号;
        [Size(30)]
        public string 合同编号
        {
            get { return f合同编号; }
            set { SetPropertyValue<string>(nameof(合同编号), ref f合同编号, value); }
        }
        string f备注;
        [Size(80)]
        public string 备注
        {
            get { return f备注; }
            set { SetPropertyValue<string>(nameof(备注), ref f备注, value); }
        }
        string f项目名称;
        [Size(80)]
        public string 项目名称
        {
            get { return f项目名称; }
            set { SetPropertyValue<string>(nameof(项目名称), ref f项目名称, value); }
        }
    }

}
