//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 系统 : XPObject
    {
        string f系统名称;
        [Size(200)]
        public string 系统名称
        {
            get { return f系统名称; }
            set { SetPropertyValue<string>(nameof(系统名称), ref f系统名称, value); }
        }
        职工 f信息中心对接人;
        public 职工 信息中心对接人
        {
            get { return f信息中心对接人; }
            set { SetPropertyValue<职工>(nameof(信息中心对接人), ref f信息中心对接人, value); }
        }
        公司 f公司;
        public 公司 公司
        {
            get { return f公司; }
            set { SetPropertyValue<公司>(nameof(公司), ref f公司, value); }
        }
        DateTime f上线时间;
        public DateTime 上线时间
        {
            get { return f上线时间; }
            set { SetPropertyValue<DateTime>(nameof(上线时间), ref f上线时间, value); }
        }
        string f功能简介;
        [Size(200)]
        public string 功能简介
        {
            get { return f功能简介; }
            set { SetPropertyValue<string>(nameof(功能简介), ref f功能简介, value); }
        }
        string f管理员用户;
        [Size(20)]
        public string 管理员用户
        {
            get { return f管理员用户; }
            set { SetPropertyValue<string>(nameof(管理员用户), ref f管理员用户, value); }
        }
        string f管理员密码;
        [Size(80)]
        public string 管理员密码
        {
            get { return f管理员密码; }
            set { SetPropertyValue<string>(nameof(管理员密码), ref f管理员密码, value); }
        }
        string f客户端进程名;
        [Size(80)]
        public string 客户端进程名
        {
            get { return f客户端进程名; }
            set { SetPropertyValue<string>(nameof(客户端进程名), ref f客户端进程名, value); }
        }
        string f链接;
        [Size(800)]
        public string 链接
        {
            get { return f链接; }
            set { SetPropertyValue<string>(nameof(链接), ref f链接, value); }
        }
        bool f是否有合同;
        public bool 是否有合同
        {
            get { return f是否有合同; }
            set { SetPropertyValue<bool>(nameof(是否有合同), ref f是否有合同, value); }
        }
        decimal f购买金额;
        public decimal 购买金额
        {
            get { return f购买金额; }
            set { SetPropertyValue<decimal>(nameof(购买金额), ref f购买金额, value); }
        }
        decimal f维保金额;
        public decimal 维保金额
        {
            get { return f维保金额; }
            set { SetPropertyValue<decimal>(nameof(维保金额), ref f维保金额, value); }
        }
        bool f合同已过期;
        public bool 合同已过期
        {
            get { return f合同已过期; }
            set { SetPropertyValue<bool>(nameof(合同已过期), ref f合同已过期, value); }
        }
        bool f实现单点登录;
        public bool 实现单点登录
        {
            get { return f实现单点登录; }
            set { SetPropertyValue<bool>(nameof(实现单点登录), ref f实现单点登录, value); }
        }
        string f备注;
        [Size(800)]
        public string 备注
        {
            get { return f备注; }
            set { SetPropertyValue<string>(nameof(备注), ref f备注, value); }
        }
        职工 f核验人;
        public 职工 核验人
        {
            get { return f核验人; }
            set { SetPropertyValue<职工>(nameof(核验人), ref f核验人, value); }
        }
        bool f已核验;
        public bool 已核验
        {
            get { return f已核验; }
            set { SetPropertyValue<bool>(nameof(已核验), ref f已核验, value); }
        }
        EType1 f类型1;
        public EType1 类型1
        {
            get { return f类型1; }
            set { SetPropertyValue<EType1>(nameof(类型1), ref f类型1, value); }
        }
        int f巡检间隔天数;
        public int 巡检间隔天数
        {
            get { return f巡检间隔天数; }
            set { SetPropertyValue<int>(nameof(巡检间隔天数), ref f巡检间隔天数, value); }
        }
        E网络运行环境 f网络运行环境;
        public E网络运行环境 网络运行环境
        {
            get { return f网络运行环境; }
            set { SetPropertyValue<E网络运行环境>(nameof(网络运行环境), ref f网络运行环境, value); }
        }
        [Association(@"服务器References系统")]
        public XPCollection<服务器> 服务器s { get { return GetCollection<服务器>(nameof(服务器s)); } }
        [Association(@"部门References系统")]
        public XPCollection<部门> 部门s { get { return GetCollection<部门>(nameof(部门s)); } }
        [Association(@"巡检References系统"), Aggregated]
        public XPCollection<巡检> 巡检s { get { return GetCollection<巡检>(nameof(巡检s)); } }
        [Association(@"系统付费References系统"), Aggregated]
        public XPCollection<系统付费> 系统付费s { get { return GetCollection<系统付费>(nameof(系统付费s)); } }
    }

}
