//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    public partial class 职工 : XPObject
    {
        string f姓名;
        [Size(80)]
        public string 姓名
        {
            get { return f姓名; }
            set { SetPropertyValue<string>(nameof(姓名), ref f姓名, value); }
        }
    }

}
