//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SystemManager.Module.BusinessObjects.ora55
{

    [MapInheritance(MapInheritanceType.ParentTable)]
    public partial class 部门 : 字典
    {
        [Association(@"部门References系统")]
        public XPCollection<系统> 系统s { get { return GetCollection<系统>(nameof(系统s)); } }
    }

}
